### ISSUE TITLE
Hide by weekday

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#42]
This feature will hide a conversation on specific weekdays, and unhide it on others.

Access: Right-click on a conversation --> hide by weekday, (located underneath "hide").

Clicking on "hide by weekday" opens a dialog where you can see the names of all the days in the week, starting from Sunday till Saturday (we beta in Israel where Sunday is the first day. In future versions this will be customizable somehow to start from Monday.)

Each day can be toggled ON/OFF (Hidden/Shown).

The days Sunday, Monday, Tuesday, Wednesday & Thursday are preselected as Hidden.

A button "Flip", when pressed, will change every ON to OFF & vice versa.

A button "Apply" will save & apply this. From now on, the conversation is hidden only on the "Hidden" days, and automatically visible on other days.

Note: If Hide is properly implemented and really doesn't appear in the list of chats, as intended - then we need some way to view all hidden chats and reconfigure this.

**Comment by ripper234** [comment]
This sounds similar to #19 , I wonder if it's duplicate or just similar.

**Comment by liatzionimorad** [comment]
Q1: "Hide conversations on specific days" is a pumped-up version of "Pulse mode", I think it's better to keep "Hide conversations on specific days". Because "Hide conversations on specific days" makes more sense.
A1:
--makes sense

assessments:
8hr - popup with week days with toggle buttons
1hr - button 'Hide by weekday'
9hr - code for check new day and hide contacts

**Comment by ripper234** [comment]
Will be implemented by #19
