### ISSUE TITLE
Whatsapp tab changes from whatsapp to url + notifications on unread messages not seen 

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#47]
![image](https://user-images.githubusercontent.com/79567202/116354508-37d3e780-a801-11eb-9f45-d4f4d91c1ac7.png)

This occurs randomly. Notification on un read messages may not appear or show wrong data. Refresh solves the issue for a while.

**Comment by FrenkiBeggins** [comment]
Hello,
We have divided error #47 (#33 in the task list) into two tasks:
33.1 Incorrect header text format. (5 hours).
33.2 Incorrect data in the counter (incorrect count of unread messages).
33.2.1 Item cannot be completed before item 28 in the task list, because it involves a high-level api.



1. The point is that previously we also needed access to the high-level api.
1.1 By high-level api we mean access to the site's memory.
2. Your extension has written code that we can work with freely. But functions which directly affect WA code are not available to us, because we don't have access to the high-level WA API. For example, task 47.2 (number 33 on the task list) is a task which is directly related to WA code and cannot be solved without it.
3. We write complex algorithms to make your extension functions work like the original WA.
4.1 At the moment we haven't found a way to access the high-level API.
4.2 You can give us permission to find workarounds for the high-level WA API described in task list #28.
4.3.1 Task #28 on the task list is to find access to the high-level API. Which will affect most of your tasks and their solutions. If, of course, we can do it.
4.3.2
 Finding solutions and time
28.1 (10hr)
28.2 (5hr)
28.3 (10 hours)
28.4 (6 hours)
5. Most of your tasks require access to a high-level WA API. If we have it: the time to solve most tasks will be significantly reduced or become the most optimal!

**Comment by ripper234** [comment]
Hi, what's the ETA on this?

1. When the code will be ready?
2. When will it be in production?

**Comment by liatzionimorad** [comment]
It is fixed. I will upload as beta version to chrome first
